"""add users table and resume/job_description ownership

Revision ID: b959caaac973
Revises: e0ce964f6fda
Create Date: 2026-09-16 16:47:43.242685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b959caaac973'
down_revision: Union[str, None] = 'e0ce964f6fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('job_descriptions', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_job_descriptions_user_id'), 'job_descriptions', ['user_id'], unique=False)
    # Named explicitly (autogenerate left this as None): this project's
    # Base has no naming_convention configured, so an unnamed constraint
    # here would make downgrade()'s drop_constraint(None, ...) below fail
    # outright - there would be no name for Alembic to target.
    op.create_foreign_key(
        'fk_job_descriptions_user_id_users', 'job_descriptions', 'users', ['user_id'], ['id'], ondelete='CASCADE'
    )
    op.add_column('resumes', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_foreign_key(
        'fk_resumes_user_id_users', 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_resumes_user_id_users', 'resumes', type_='foreignkey')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.drop_column('resumes', 'user_id')
    op.drop_constraint('fk_job_descriptions_user_id_users', 'job_descriptions', type_='foreignkey')
    op.drop_index(op.f('ix_job_descriptions_user_id'), table_name='job_descriptions')
    op.drop_column('job_descriptions', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
