"""create phase 9b application schema

Revision ID: e0ce964f6fda
Revises: 
Create Date: 2026-09-16 14:46:23.984433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0ce964f6fda'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_job_title'), 'job_descriptions', ['job_title'], unique=False)
    op.create_table('resumes',
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resumes_email'), 'resumes', ['email'], unique=False)
    op.create_table('job_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=False),
    sa.Column('requirement', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category in ('required_skill', 'preferred_skill', 'education', 'experience', 'certification', 'language')", name='ck_job_requirements_category'),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_requirements_category'), 'job_requirements', ['category'], unique=False)
    op.create_index(op.f('ix_job_requirements_job_description_id'), 'job_requirements', ['job_description_id'], unique=False)
    op.create_table('resume_analyses',
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('job_description_id', sa.UUID(), nullable=False),
    sa.Column('deterministic_score', sa.Float(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('combined_score', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_description_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_analyses_job_description_id'), 'resume_analyses', ['job_description_id'], unique=False)
    op.create_index('ix_resume_analyses_resume_id_job_description_id', 'resume_analyses', ['resume_id', 'job_description_id'], unique=False)
    op.create_table('resume_certifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_certifications_resume_id'), 'resume_certifications', ['resume_id'], unique=False)
    op.create_table('resume_education',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('degree', sa.String(length=255), nullable=True),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.Column('field', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_education_resume_id'), 'resume_education', ['resume_id'], unique=False)
    op.create_table('resume_experience',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_experience_resume_id'), 'resume_experience', ['resume_id'], unique=False)
    op.create_table('resume_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('proficiency', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_languages_resume_id'), 'resume_languages', ['resume_id'], unique=False)
    op.create_table('resume_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('technologies', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_projects_resume_id'), 'resume_projects', ['resume_id'], unique=False)
    op.create_table('resume_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('skill', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=20), server_default='parsed', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source in ('parsed', 'manual')", name='ck_resume_skills_source'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'skill', name='uq_resume_skills_resume_id_skill')
    )
    op.create_index(op.f('ix_resume_skills_skill'), 'resume_skills', ['skill'], unique=False)
    op.create_table('analysis_skill_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('requirement', sa.String(length=500), nullable=False),
    sa.Column('matched_resume_skill', sa.String(length=255), nullable=True),
    sa.Column('similarity', sa.Float(), nullable=True),
    sa.Column('matched', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.CheckConstraint("category in ('skills', 'experience', 'projects', 'education', 'certifications')", name='ck_analysis_skill_results_category'),
    sa.ForeignKeyConstraint(['analysis_id'], ['resume_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_skill_results_analysis_id'), 'analysis_skill_results', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_skill_results_category'), 'analysis_skill_results', ['category'], unique=False)
    op.create_table('analysis_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('recommendations_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['analysis_id'], ['resume_analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('analysis_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('analysis_summaries')
    op.drop_index(op.f('ix_analysis_skill_results_category'), table_name='analysis_skill_results')
    op.drop_index(op.f('ix_analysis_skill_results_analysis_id'), table_name='analysis_skill_results')
    op.drop_table('analysis_skill_results')
    op.drop_index(op.f('ix_resume_skills_skill'), table_name='resume_skills')
    op.drop_table('resume_skills')
    op.drop_index(op.f('ix_resume_projects_resume_id'), table_name='resume_projects')
    op.drop_table('resume_projects')
    op.drop_index(op.f('ix_resume_languages_resume_id'), table_name='resume_languages')
    op.drop_table('resume_languages')
    op.drop_index(op.f('ix_resume_experience_resume_id'), table_name='resume_experience')
    op.drop_table('resume_experience')
    op.drop_index(op.f('ix_resume_education_resume_id'), table_name='resume_education')
    op.drop_table('resume_education')
    op.drop_index(op.f('ix_resume_certifications_resume_id'), table_name='resume_certifications')
    op.drop_table('resume_certifications')
    op.drop_index('ix_resume_analyses_resume_id_job_description_id', table_name='resume_analyses')
    op.drop_index(op.f('ix_resume_analyses_job_description_id'), table_name='resume_analyses')
    op.drop_table('resume_analyses')
    op.drop_index(op.f('ix_job_requirements_job_description_id'), table_name='job_requirements')
    op.drop_index(op.f('ix_job_requirements_category'), table_name='job_requirements')
    op.drop_table('job_requirements')
    op.drop_index(op.f('ix_resumes_email'), table_name='resumes')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_job_descriptions_job_title'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
